### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by emilyamorris** [emilyamorris/mini_project_4#1]
-Look and see if movies based on books do better in the opening weekend/gross than movies not based on books
-Look at what studios do more book-based movies
-Look at budget of book-based movies vs non book-based movies vs how well they do
-Look at ratings of movies based on books, do ratings correlate with gross? 
-Countries that tend to get book-based movies

-include lil plot about my mom cus she's in the database

**Comment by slednicky** [comment]
omg my mom is also in IMDB :) small world 

https://www.imdb.com/name/nm0496600/
